### PR TITLE
Issue/7 Add skeleton code for the CI (GitHandler) class

### LINKED ISSUE #7: Create class skeleton for the CI class

### PR DESCRIPTION
**Pull request by agylling**
Fixes #7

### CODE REVIEW

**Review by mackeper — APPROVED** [review]
Looks good

**Review by mstniy — COMMENTED** [review]
It seems the functions take too few arguments. For example, how will send_notification know if it should send a success message of a failure message? It sounds unwise to keep this kind of information in GitEvent, as it is not provide by GitHub.

**Comment by agylling** [comment]
Sure, would you like a String parameter or a boolean?

**Comment by mstniy** [comment]
I'd imagine something like
public static void request_push(GitEvent G);
public static string pull_branch(GitEvent G); // Returns the path of the branch (on the disk)
public static bool build_branch(GitEvent G, String path); // Returns whether the build succeeded
public static bool start_tests(GitEvent G, String path); // Returns whether the tests succeeded
public static bool send_notification(GitEvent G, String message); // Returns whether the send succeeded. Send the message to only the author

Or the GitEvent can be a member field of GitHandler

**Review by mstniy — APPROVED** [review]
Seems good

**Pull request merged**
